#include<iostream>
using namespace std;

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
    char findTheDifference(string s, string t) {
        int sum = 0;
        for(auto val: s) {
            sum += val-'a';
        }
        for(auto val: t) {
            sum -= val-'a';
        }
        
        return abs(sum)+'a';
    }
int main() {
    string s = "abcd";
    string t = "abcde";

    cout<<"The difference in "<<s<<" and "<<t<<" is '"<<findTheDifference(s,t)<<"'"<<endl;;
}